"""Domain constants."""

RSS_SOURCES = [
    {"name": "InfoMoney", "feed_url": "https://www.infomoney.com.br/feed/", "language": "pt-BR", "market": "B3", "is_active": True},
    {"name": "Valor", "feed_url": "https://valor.globo.com/rss/valor/", "language": "pt-BR", "market": "B3", "is_active": True},
    {"name": "Exame", "feed_url": "https://exame.com/rss/", "language": "pt-BR", "market": "B3", "is_active": True},
    {"name": "O Globo Economia", "feed_url": "https://blogs.oglobo.globo.com/economia/rss/", "language": "pt-BR", "market": "B3", "is_active": True},
    {"name": "Investing BR", "feed_url": "https://br.investing.com/rss/news_1.rss", "language": "pt-BR", "market": "B3", "is_active": True},
    {"name": "Reuters Markets", "feed_url": "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=reuters-update", "language": "en", "market": None, "is_active": True},
    {"name": "MarketWatch", "feed_url": "https://feeds.content.dowjones.io/public/rss/mw_topalert", "language": "en", "market": None, "is_active": True},
    {"name": "Yahoo Finance US", "feed_url": "https://www.yahoo.com/news/rss/category-stocks", "language": "en", "market": None, "is_active": True},
]

ALL_ASSETS = [
    # ======================== BRASIL (B3) ========================
    {"symbol": "PETR4.SA", "display_symbol": "PETR4", "name": "Petrobras PN", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "VALE3.SA", "display_symbol": "VALE3", "name": "Vale ON", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "ITUB4.SA", "display_symbol": "ITUB4", "name": "Itaú Unibanco PN", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "BBDC4.SA", "display_symbol": "BBDC4", "name": "Bradesco PN", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "BBAS3.SA", "display_symbol": "BBAS3", "name": "Banco do Brasil", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "ABEV3.SA", "display_symbol": "ABEV3", "name": "Ambev SA", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "B3SA3.SA", "display_symbol": "B3SA3", "name": "B3 - Bolsa do Brasil", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "MGLU3.SA", "display_symbol": "MGLU3", "name": "Magazine Luiza", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "HYPE3.SA", "display_symbol": "HYPE3", "name": "Hypera Pharma", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "RENT3.SA", "display_symbol": "RENT3", "name": "Localiza", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "LREN3.SA", "display_symbol": "LREN3", "name": "Lojas Renner", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "RADL3.SA", "display_symbol": "RADL3", "name": "Raia Drogasil", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "EQTL3.SA", "display_symbol": "EQTL3", "name": "Equatorial Energia", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "ELET3.SA", "display_symbol": "ELET3", "name": "Eletrobras", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "KLBN11.SA", "display_symbol": "KLBN11", "name": "Klabin Unit", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "SUZB3.SA", "display_symbol": "SUZB3", "name": "Suzano Papel", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "CSNA3.SA", "display_symbol": "CSNA3", "name": "CSN", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "USIM5.SA", "display_symbol": "USIM5", "name": "Usiminas", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "GGBR4.SA", "display_symbol": "GGBR4", "name": "Gerdau PN", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "GOAU4.SA", "display_symbol": "GOAU4", "name": "Metalurgica Gerdau", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "CMIG4.SA", "display_symbol": "CMIG4", "name": "Cemig PN", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "EGIE3.SA", "display_symbol": "EGIE3", "name": "Engie Brasil", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "TAEE11.SA", "display_symbol": "TAEE11", "name": "Taesa", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "SAPR11.SA", "display_symbol": "SAPR11", "name": "Sanepar", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "BPAC11.SA", "display_symbol": "BPAC11", "name": "BTG Pactual Unit", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "BPAN4.SA", "display_symbol": "BPAN4", "name": "Banco Pan", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "CIEL3.SA", "display_symbol": "CIEL3", "name": "Cielo", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "RAIL3.SA", "display_symbol": "RAIL3", "name": "Rumo Logística", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "JBSS3.SA", "display_symbol": "JBSS3", "name": "JBS", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "MRFG3.SA", "display_symbol": "MRFG3", "name": "Marfrig", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "BRFS3.SA", "display_symbol": "BRFS3", "name": "BR Foods", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "ARZZ3.SA", "display_symbol": "ARZZ3", "name": "Arezzo", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "HBSA3.SA", "display_symbol": "HBSA3", "name": "Hapvida", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "CRFB3.SA", "display_symbol": "CRFB3", "name": "Carrefour Brasil", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "PCAR3.SA", "display_symbol": "PCAR3", "name": "Pão de Açúcar", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "SBSP3.SA", "display_symbol": "SBSP3", "name": "Sabesp", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "HAPV3.SA", "display_symbol": "HAPV3", "name": "Hapvida", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "FLRY3.SA", "display_symbol": "FLRY3", "name": "Fleury", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "MDIA3.SA", "display_symbol": "MDIA3", "name": "M. Dias Branco", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "WEGE3.SA", "display_symbol": "WEGE3", "name": "WEG Equipamentos", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "TOTS3.SA", "display_symbol": "TOTS3", "name": "Tótvs", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "POSI3.SA", "display_symbol": "POSI3", "name": "Positivo Tec.", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "LWSA3.SA", "display_symbol": "LWSA3", "name": "Locaweb", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "PETZ3.SA", "display_symbol": "PETZ3", "name": "Petz", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "VVAR3.SA", "display_symbol": "VVAR3", "name": "Via Varejo", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "AMER3.SA", "display_symbol": "AMER3", "name": "Americanas", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "SIMH3.SA", "display_symbol": "SIMH3", "name": "Simpar", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "MOVI3.SA", "display_symbol": "MOVI3", "name": "Mobilias", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "ODPV3.SA", "display_symbol": "ODPV3", "name": "Odontoprev", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "POMO4.SA", "display_symbol": "POMO4", "name": "Marcopolo", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "ASHR3.SA", "display_symbol": "ASHR3", "name": "Athenas Saúde", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "AZUL4.SA", "display_symbol": "AZUL4", "name": "Azul Linhas Aéreas", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "GOLL4.SA", "display_symbol": "GOLL4", "name": "Gol Linhas Aéreas", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "CVCB3.SA", "display_symbol": "CVCB3", "name": "CVC Brasil", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "CYRE3.SA", "display_symbol": "CYRE3", "name": "Cyrela Brazil", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "MRVE3.SA", "display_symbol": "MRVE3", "name": "MRV Engenharia", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "DIRR3.SA", "display_symbol": "DIRR3", "name": "Direcional Engenharia", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "TCSA3.SA", "display_symbol": "TCSA3", "name": "Tecnospeed", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "ALSO3.SA", "display_symbol": "ALSO3", "name": "Aliansce Sonae", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "IGTI11.SA", "display_symbol": "IGTI11", "name": "Iguateam", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "MULT3.SA", "display_symbol": "MULT3", "name": "Multiplan", "market": "B3", "asset_type": "stock", "currency": "BRL"},
    {"symbol": "BOVA11.SA", "display_symbol": "BOVA11", "name": "iShares Ibovespa", "market": "B3", "asset_type": "etf", "currency": "BRL"},
    {"symbol": "SMAL11.SA", "display_symbol": "SMAL11", "name": "iShares Small Cap", "market": "B3", "asset_type": "etf", "currency": "BRL"},
    {"symbol": "IVVB11.SA", "display_symbol": "IVVB11", "name": "iShares S&P 500", "market": "B3", "asset_type": "etf", "currency": "BRL"},
    {"symbol": "HASH11.SA", "display_symbol": "HASH11", "name": "Hashdex NDRIFT", "market": "B3", "asset_type": "etf", "currency": "BRL"},
    # ======================== EUA (NYSE/NASDAQ) ========================
    {"symbol": "AAPL", "display_symbol": "AAPL", "name": "Apple Inc.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "MSFT", "display_symbol": "MSFT", "name": "Microsoft Corp.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "GOOGL", "display_symbol": "GOOGL", "name": "Alphabet Class A", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "AMZN", "display_symbol": "AMZN", "name": "Amazon.com", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "META", "display_symbol": "META", "name": "Meta Platforms", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "NVDA", "display_symbol": "NVDA", "name": "NVIDIA Corp.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "TSLA", "display_symbol": "TSLA", "name": "Tesla Inc.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BRK-B", "display_symbol": "BRK.B", "name": "Berkshire Hathaway B", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "JPM", "display_symbol": "JPM", "name": "JPMorgan Chase", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "V", "display_symbol": "V", "name": "Visa Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "MA", "display_symbol": "MA", "name": "Mastercard Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "JNJ", "display_symbol": "JNJ", "name": "Johnson & Johnson", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "WMT", "display_symbol": "WMT", "name": "Walmart Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "PG", "display_symbol": "PG", "name": "Procter & Gamble", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "HD", "display_symbol": "HD", "name": "Home Depot", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "KO", "display_symbol": "KO", "name": "Coca-Cola Co.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "PEP", "display_symbol": "PEP", "name": "PepsiCo Inc.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "MCD", "display_symbol": "MCD", "name": "McDonald's Corp.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "NKE", "display_symbol": "NKE", "name": "Nike Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "DIS", "display_symbol": "DIS", "name": "Walt Disney Co.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "NFLX", "display_symbol": "NFLX", "name": "Netflix Inc.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BAC", "display_symbol": "BAC", "name": "Bank of America", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "XOM", "display_symbol": "XOM", "name": "Exxon Mobil", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "CVX", "display_symbol": "CVX", "name": "Chevron Corp.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "PFE", "display_symbol": "PFE", "name": "Pfizer Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "MRK", "display_symbol": "MRK", "name": "Merck & Co.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "ABBV", "display_symbol": "ABBV", "name": "AbbVie Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "LLY", "display_symbol": "LLY", "name": "Eli Lilly & Co.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "TMO", "display_symbol": "TMO", "name": "Thermo Fisher", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "AVGO", "display_symbol": "AVGO", "name": "Broadcom Inc.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "COST", "display_symbol": "COST", "name": "Costco Wholesale", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "ABT", "display_symbol": "ABT", "name": "Abbott Laboratories", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "CRM", "display_symbol": "CRM", "name": "Salesforce Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "ADBE", "display_symbol": "ADBE", "name": "Adobe Inc.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "INTC", "display_symbol": "INTC", "name": "Intel Corp.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "CSCO", "display_symbol": "CSCO", "name": "Cisco Systems", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "ORCL", "display_symbol": "ORCL", "name": "Oracle Corp.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "AMD", "display_symbol": "AMD", "name": "Advanced Micro Devices", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "QCOM", "display_symbol": "QCOM", "name": "Qualcomm Inc.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "TXN", "display_symbol": "TXN", "name": "Texas Instruments", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "IBM", "display_symbol": "IBM", "name": "Intl. Business Machines", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "GS", "display_symbol": "GS", "name": "Goldman Sachs", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "MS", "display_symbol": "MS", "name": "Morgan Stanley", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "C", "display_symbol": "C", "name": "Citigroup Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "WFC", "display_symbol": "WFC", "name": "Wells Fargo", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "AXP", "display_symbol": "AXP", "name": "American Express", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "UAL", "display_symbol": "UAL", "name": "United Airlines", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "DAL", "display_symbol": "DAL", "name": "Delta Air Lines", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SBUX", "display_symbol": "SBUX", "name": "Starbucks Corp.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "LOW", "display_symbol": "LOW", "name": "Lowe's Companies", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "TGT", "display_symbol": "TGT", "name": "Target Corp.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "F", "display_symbol": "F", "name": "Ford Motor Co.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "GM", "display_symbol": "GM", "name": "General Motors", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BA", "display_symbol": "BA", "name": "Boeing Co.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "CAT", "display_symbol": "CAT", "name": "Caterpillar Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "GE", "display_symbol": "GE", "name": "General Electric", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "UPS", "display_symbol": "UPS", "name": "United Parcel Service", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "PYPL", "display_symbol": "PYPL", "name": "PayPal Holdings", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SHOP", "display_symbol": "SHOP", "name": "Shopify Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SQ", "display_symbol": "SQ", "name": "Block Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "UBER", "display_symbol": "UBER", "name": "Uber Technologies", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "ABNB", "display_symbol": "ABNB", "name": "Airbnb Inc.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "ZM", "display_symbol": "ZM", "name": "Zoom Video Comms.", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SNOW", "display_symbol": "SNOW", "name": "Snowflake Inc.", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "PLTR", "display_symbol": "PLTR", "name": "Palantir Technologies", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "COIN", "display_symbol": "COIN", "name": "Coinbase Global", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SPY", "display_symbol": "SPY", "name": "SPDR S&P 500 ETF", "market": "NYSE", "asset_type": "etf", "currency": "USD"},
    {"symbol": "QQQ", "display_symbol": "QQQ", "name": "Invesco QQQ ETF", "market": "NASDAQ", "asset_type": "etf", "currency": "USD"},
    {"symbol": "DIA", "display_symbol": "DIA", "name": "SPDR Dow Jones ETF", "market": "NYSE", "asset_type": "etf", "currency": "USD"},
    {"symbol": "IWM", "display_symbol": "IWM", "name": "iShares Russell 2000", "market": "NYSE", "asset_type": "etf", "currency": "USD"},
    {"symbol": "VTI", "display_symbol": "VTI", "name": "Vanguard Total Market", "market": "NYSE", "asset_type": "etf", "currency": "USD"},
    {"symbol": "VWO", "display_symbol": "VWO", "name": "Vanguard Emerging Mkts", "market": "NYSE", "asset_type": "etf", "currency": "USD"},
    # ======================== EUROPA (LSE/Euronext/XETRA) ========================
    {"symbol": "ASML", "display_symbol": "ASML", "name": "ASML Holding", "market": "NASDAQ", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SAP.DE", "display_symbol": "SAP", "name": "SAP SE", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SIE.DE", "display_symbol": "SIE", "name": "Siemens AG", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "ALV.DE", "display_symbol": "ALV", "name": "Allianz SE", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BMW.DE", "display_symbol": "BMW", "name": "BMW AG", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "VOW3.DE", "display_symbol": "VOW3", "name": "Volkswagen AG", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "DAI.DE", "display_symbol": "DAI", "name": "Mercedes-Benz Group", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "DBK.DE", "display_symbol": "DBK", "name": "Deutsche Bank", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BAS.DE", "display_symbol": "BAS", "name": "BASF SE", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BAYN.DE", "display_symbol": "BAYN", "name": "Bayer AG", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "IFX.DE", "display_symbol": "IFX", "name": "Infineon Technologies", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SAP.PA", "display_symbol": "SAP", "name": "SAP SE (Paris)", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "MC.PA", "display_symbol": "MC", "name": "LVMH Moët Hennessy", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "OR.PA", "display_symbol": "OR", "name": "L'Oréal SA", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "TTE.PA", "display_symbol": "TTE", "name": "TotalEnergies SE", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "AIR.PA", "display_symbol": "AIR", "name": "Airbus SE", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BN.PA", "display_symbol": "BN", "name": "Danone SA", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "FP.PA", "display_symbol": "FP", "name": "TotalEnergies (Paris)", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "RACE", "display_symbol": "RACE", "name": "Ferrari NV", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    # ---------- UK (LSE via LON) ----------
    {"symbol": "HSBA.L", "display_symbol": "HSBA", "name": "HSBC Holdings", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BP.L", "display_symbol": "BP", "name": "BP plc", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SHEL.L", "display_symbol": "SHEL", "name": "Shell plc", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "AZN.L", "display_symbol": "AZN", "name": "AstraZeneca plc", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "ULVR.L", "display_symbol": "ULVR", "name": "Unilever plc", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "GSK.L", "display_symbol": "GSK", "name": "GSK plc", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    # ---------- ADRs (US-listed foreign) ----------
    {"symbol": "NVO", "display_symbol": "NVO", "name": "Novo Nordisk ADR", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "TSM", "display_symbol": "TSM", "name": "Taiwan Semiconductor", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BABA", "display_symbol": "BABA", "name": "Alibaba Group ADR", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "TCEHY", "display_symbol": "TCEHY", "name": "Tencent Holdings ADR", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "AEM", "display_symbol": "AEM", "name": "Agnico Eagle Mines", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "GOLD", "display_symbol": "GOLD", "name": "Barrick Gold", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "RIO", "display_symbol": "RIO", "name": "Rio Tinto", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "TEF", "display_symbol": "TEF", "name": "Telefónica SA", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "BBVA", "display_symbol": "BBVA", "name": "Banco Bilbao Vizcaya", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "SNY", "display_symbol": "SNY", "name": "Sanofi ADR", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    {"symbol": "ING", "display_symbol": "ING", "name": "ING Groep ADR", "market": "NYSE", "asset_type": "stock", "currency": "USD"},
    # ======================== CRIPTO ========================
    {"symbol": "BTC-USD", "display_symbol": "BTC", "name": "Bitcoin", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    {"symbol": "ETH-USD", "display_symbol": "ETH", "name": "Ethereum", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    {"symbol": "BNB-USD", "display_symbol": "BNB", "name": "BNB", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    {"symbol": "SOL-USD", "display_symbol": "SOL", "name": "Solana", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    {"symbol": "XRP-USD", "display_symbol": "XRP", "name": "Ripple", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    {"symbol": "ADA-USD", "display_symbol": "ADA", "name": "Cardano", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    {"symbol": "DOGE-USD", "display_symbol": "DOGE", "name": "Dogecoin", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    {"symbol": "DOT-USD", "display_symbol": "DOT", "name": "Polkadot", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    {"symbol": "MATIC-USD", "display_symbol": "MATIC", "name": "Polygon", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    {"symbol": "LINK-USD", "display_symbol": "LINK", "name": "Chainlink", "market": "CRYPTO", "asset_type": "crypto", "currency": "USD"},
    # ======================== FOREX & COMMODITIES ========================
    {"symbol": "EURUSD=X", "display_symbol": "EURUSD", "name": "EUR/USD", "market": "FOREX", "asset_type": "forex", "currency": "USD"},
    {"symbol": "USDJPY=X", "display_symbol": "USDJPY", "name": "USD/JPY", "market": "FOREX", "asset_type": "forex", "currency": "USD"},
    {"symbol": "GBPUSD=X", "display_symbol": "GBPUSD", "name": "GBP/USD", "market": "FOREX", "asset_type": "forex", "currency": "USD"},
    {"symbol": "USDBRL=X", "display_symbol": "USDBRL", "name": "USD/BRL", "market": "FOREX", "asset_type": "forex", "currency": "USD"},
    {"symbol": "GC=F", "display_symbol": "GOLD", "name": "Gold Futures", "market": "COMMODITY", "asset_type": "commodity", "currency": "USD"},
    {"symbol": "SI=F", "display_symbol": "SILVER", "name": "Silver Futures", "market": "COMMODITY", "asset_type": "commodity", "currency": "USD"},
    {"symbol": "CL=F", "display_symbol": "WTI", "name": "Crude Oil WTI", "market": "COMMODITY", "asset_type": "commodity", "currency": "USD"},
    {"symbol": "NG=F", "display_symbol": "NATGAS", "name": "Natural Gas", "market": "COMMODITY", "asset_type": "commodity", "currency": "USD"},
]

# Top suggested for empty watchlists (subset)
SUGGESTED_ASSETS = ALL_ASSETS[:30]